### ISSUE TITLE
Create button object with click code

### ISSUE THREAD

**Issue by Phabbits** [famegames/squared#108]
I have found that a good way to make a flexible menu is to have an `obj_button` that can represents different varieties of buttons, and is stored in a list in the `obj_menu`. This helps greatly in implementing both mouse and keyboard input for navigating the menu, because each button can check for a click, and `obj_menu` can scroll through the buttons with the keyboard input.
The click code is that in the button object, I have found a good way to track the clicking which is to have the action of clicking defined in a user defined event, which is called upon when left clicked on, or when `obj_menu` says it is. To program this click code I would recommend to have it so that when the button is left clicked on, it calls the user defined event.

The button object will also need two variables, title and action. The title variable will tell the button what to draw on itself, and the action variable will hold a string which will inform the button what action to carry out when clicked.

**Comment by Regulator13** [comment]
There's already a GM defined event for clicking, why make a user one?

**Comment by Regulator13** [comment]
Are you suggesting a DS list for `obj_menu`?

**Comment by Regulator13** [comment]
I don't understand the need for dual implementation so early either, why not make users use a mouse for now, it's not that big of a deal

**Comment by Phabbits** [comment]
I do suggest that a DS list is created in `obj_menu` to allow for some keyboard input code.
The GM defined event will be used for clicking, but the actual code it carries out will need to be place inside a user defined event, so that the keyboard clicking can also call that same event.
Although it is not necessary to have this "dual implementation" early, it is not a burden to code, and I believe that one should always make their code as flexible as possible.
