### ISSUE TITLE
Implement a system of states for obj_menu

### ISSUE THREAD

**Issue by Phabbits** [famegames/squared#116]
I have found that an efficient way to keep track of where the player currently is in the menu, is using a system of states. These states will tell the game whether the player is in one of the menus, or in the actually game itself.
For this game the following states that I thought would be good to have would include:

- STATE_MAIN - the main menu
- STATE_ONLINE - the online menu where players can host or join a server
- STATE_LOBBY - the lobby where joined players, local or online, can wait before the game starts
- STATE_GAME - the actual game
- STATE_SCORE - post game scores

These states have been listed with all caps to show that they should probably be predefined constants, or macros. This will allow us to use simple integers to indicate the different states, while maintaining easy readable for the programmers. We want simple integers to reduce the time it would take to run each check with a state, where as using something like strings to describe the states would result in a lot of loops for the compiler to check (CS 159).

`obj_menu` would then just have one state variable, like `state = STATE_MAIN`, which could be used with switch or if statements when needed.

To define these macros, I think that we should do them all in one spot, like maybe in a new object, or obj_main. For example
```gml
// menu state maros
#macro STATE_MAIN 0
#macro STATE_ONLINE 1
#macro STATE_LOBBY 2
```

**Comment by Regulator13** [comment]
What is the purpose of this? Why does the game need to know where the player is at?

**Comment by Phabbits** [comment]
It is important to know where the player in terms of menu, for not only input on different menus, and any special displays, but also with networking to keep all players on the same page.
