### ISSUE TITLE
What will networking interfere with?

### ISSUE THREAD

**Issue by Regulator13** [famegames/squared#12]
What all can we not program because of networking?

**Comment by Phabbits** [comment]
The way that we previously discussed networking would be to have a simulation of the game not only running on the server, but also the clients. I believe that the best way to incorporate this method of networking into the game is to have the clients send not the input, but the current position and state of their character, and the bullets created will be sent. Also if the AI interact at all with the players, their information will also be synced. This can be discussed more latter if need. Right now a running list of objects would include:
- [ ] obj_main
- [ ] obj_player
- [ ] obj_bulletLocal
- [ ] obj_bulletNetwork
All the networking objects, obj_client, obj_server, etc.
