### ISSUE TITLE
Fix inventory

### ISSUE THREAD

**Issue by Regulator13** [famegames/squared#132]
*Context:* I was adding upgrades and realized the display of the sprites was not compatible with our current method.

*Problem:* The sprite display in the inventory depends on the `image_index` of the object that is being displayed. This is not flexible and will present issues future addition of items and upgrades.

*Solution:* @Phabbits suggested moving the burden of inventory display to the items themselves which are currently stored off screen. These items will decide where they should be drawn in the inventory based on the inventory status when they are picked up.

**Comment by Phabbits** [comment]
I find this context quite confusing. Why would the display of sprites not be compatible with our "current method"?

**Comment by Regulator13** [comment]
Good question @Phabbits, let me elaborate. Currently the sprites display on the inventory by using the `image_index` of the object that is being picked up. For example, the weapons were made on 1 sprite, with 3 indices and the index was passed over to the inventory. But the upgrades are on a new sprite, so the index of the upgrade doesn't match the index of the item display. This is a bad system so it needs to be fixed.  Since you suggested it, maybe you could fix it @Phabbits.
