### ISSUE TITLE
Merging is not possible

### ISSUE THREAD

**Issue by curteckstein** [famegames/squared#143]
**Context** 
I cannot update from default branch and because of theism code won't open and I cannot contribute 

**Problem or idea**
error: Merging is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

**Solution or next step**
I need to merge files, Im not sure how to do this.

**Comment by curteckstein** [comment]
Solution:
Through terminal I was able to merge the files and get past this issue. However, gml2 still could not run the code and ultimately Curt branch was terminated and had to be restarted.

**Comment by Regulator13** [comment]
@curteckstein is this closed now or do you still have questions?

**Comment by curteckstein** [comment]
Closed
