### ISSUE TITLE
Create par_toolModular

### ISSUE THREAD

**Issue by Regulator13** [famegames/squared#38]
child of par_tool, parent of obj_shotgun, obj_machineGun, obj_sniper

**Comment by Regulator13** [comment]
What is this object for?

**Comment by Phabbits** [comment]
I see now that I have not made myself clear in the original parent tree, I will expand upon it further here.
The obj_weapon, is supposed to be a parent for all "tools", equipable items, that can receive an upgrade. To clarify this I think we should change the name to par_toolModular.

**Comment by Regulator13** [comment]
Alright sounds good.
