### ISSUE TITLE
Create sprite for shotgun, machineGun, and sniper

### ISSUE THREAD

**Issue by Regulator13** [famegames/squared#40]
spr_shotgun, spr_machineGun, and spr_sniper

**Comment by Regulator13** [comment]
Are these to be picked up as items or are we having the player look different depending on the gun he is carrying

**Comment by Phabbits** [comment]
These are to be picked up as items. I believe that the best way to do the sprites, is to have the player be two different 32x32 sprites. The first being his body, and the second being his arm. This will allow his arm to rotate freely from his body to represent aiming. As for the guns, I believe that they should be 16x16 centered sprites, that will be drawn rotated according to the position of the character's hand when equipped, and that same sprite can be used to represent the gun on both the map and inventory.
