### ISSUE TITLE
New branch for networking code additon.

### ISSUE THREAD

**Issue by Phabbits** [famegames/squared#83]
I see that we created a specific branch for the big inventory update, I was wondering if we should do the same. The benefits that I can see are that it will let whoever is working on networking make commits easily, and without worry of the master code. The downsides that I can see are that the networking code will have to work closely with the picking up of items, and will be affecting that code. If that part of the game is changed significantly while the networking code is being made, this can lead to problems on the final merge. Thoughts?

**Comment by Regulator13** [comment]
I think a new branch would be appropriate. The downsides still apply if the code is updated directly to master. People might be able to see them more easily but they could also update from the networking branch if they wanted to build on those changes.

**Comment by Phabbits** [comment]
It is decided then, a new branch for networking. It will be created when the first issue is tackled.
