### ISSUE TITLE
There should be some way for players to drop items

### ISSUE THREAD

**Issue by Phabbits** [famegames/squared#84]
I am not exactly sure how we want to do this. We may be able to implement a dragging system, and have the player drag the items out of the inventory to drop them.

**Comment by Regulator13** [comment]
But that means we have to add dragging, what about like pressing the middle mouse button over an object. It would be easy to implement and difficult to do by accident.

**Comment by Phabbits** [comment]
That is true and would be a good way to implement it fast. Shouldn't be that hard to do, just move the item instance to the player's coordinates, and remove the id from the inventory.
