### ISSUE TITLE
AI player interaction?

### ISSUE THREAD

**Issue by Phabbits** [famegames/squared#86]
In the previous squared game the only response an AI would have to the player would be to set a shield. What sort of responses do we think the AI will have with the player? This is necessary to know what variables to account for in networking.

**Comment by Regulator13** [comment]
Didn't certain AI also move towards the player? I imagine the following:
- player's location
- location of the bullets
- maybe certain item interactions

**Comment by Regulator13** [comment]
I think we're going to focus on just the player's location and whether or not the enemy was just damaged, this will keep networking fairly simple and still give some flexibility for AI.
