### ISSUE TITLE
'Cool' upgrades?

### ISSUE THREAD

**Issue by Regulator13** [famegames/squared#9]

**Comment by Regulator13** [comment]
- Homing Bullets
- Explode on impact
- Multishot
- Persist damage

**Comment by Phabbits** [comment]
These 'Cool' upgrades will need a more reasonable name when programming in the game. I suggest the following:
- [ ] powers
- [ ] abilites

**Comment by Regulator13** [comment]
These abilities could even be two-tiered. That is a level 1 and level 2 homing bullets, level 1 and level 2 multishot, etc. Here's my thoughts for those levels:

| Ability | Level 1 description | Level 2 description |
| ------------- | -------------------- | ----------------------|
| Homing Bullets | Follow slightly | Follow more precisely |
| Explode on impact | Explode a little | Explode a lot |
| Multishot | Shoot two bullets, one over the other | Shoot 3 bullets |
| Persist Damage | Persists for a little bit | Persists longer |

Best part is these all can be combined without issue. That's 8 potential upgrades per gun!

**Comment by Regulator13** [comment]
These are all now implemented, if someone wants more they can open a new issue.
